### ISSUE TITLE
Project naming question

### ISSUE THREAD

**Issue by djKooks** [meilisearch/tokenizer#25]
Hello.

How do you think about naming the project with `camel_case`? Currently `Tokenizer` is starting with capital letter...
https://doc.rust-lang.org/1.0.0/style/style/naming/README.html

This is just a question, so if there is a specific reason, just ignore it 🙏

**Comment by curquiza** [comment]
Hello @djKooks, sorry for this huuuuge delay 😅 
You're completely right to question the repository naming. We named it first with a capitalized letter to be consistent with `MeiliSearch` but after discussion, we would rather rename it into `tokenizer` instead of `Tokenizer` to be consistent with all the other repos (except MeiliSearch of course) of the organization.
Thanks for your feedback, I'm closing this then
